#############################################################################
# Makefile for building: liblowenergyscanner_armeabi-v7a.so
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  lowenergyscanner.pro
# Template: app
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = D:\android-sdk_r24.4.1-windows\android-sdk-windows\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang
CXX           = D:\android-sdk_r24.4.1-windows\android-sdk-windows\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_BLUETOOTH_LIB -DQT_CORE_LIB
CFLAGS        = -target armv7a-linux-androideabi21 -fno-limit-debug-info -fPIC -fstack-protector-strong -DANDROID -g -marm -O0 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -target armv7a-linux-androideabi21 -fno-limit-debug-info -fPIC -fstack-protector-strong -DANDROID -g -marm -O0 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../Qt/Qt5.14.2/5.14.2/android/include -I../Qt/Qt5.14.2/5.14.2/android/include/QtQuick -I../Qt/Qt5.14.2/5.14.2/android/include/QtGui -I../Qt/Qt5.14.2/5.14.2/android/include/QtQmlModels -I../Qt/Qt5.14.2/5.14.2/android/include/QtQml -I../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork -I../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth -I../Qt/Qt5.14.2/5.14.2/android/include/QtCore -Iarmeabi-v7a -I../Qt/Qt5.14.2/5.14.2/android/mkspecs/android-clang
QMAKE         = D:/Qt/Qt5.14.2/5.14.2/android/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = D:/Qt/Qt5.14.2/5.14.2/android/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = D:/Qt/Qt5.14.2/5.14.2/android/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = liblowenergyscanner_armeabi-v7a.so1.0.0
DISTDIR = D:/lowenergyscanner/armeabi-v7a/liblowenergyscanner_armeabi-v7a.so1.0.0
LINK          = D:\android-sdk_r24.4.1-windows\android-sdk-windows\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -target armv7a-linux-androideabi21 -fno-limit-debug-info
LFLAGS        = -Wl,-soname,liblowenergyscanner_armeabi-v7a.so -Wl,-rpath-link=D:/Qt/Qt5.14.2/5.14.2/android/lib -Wl,--build-id=sha1 -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) D:/Qt/Qt5.14.2/5.14.2/android/lib/libQt5Quick_armeabi-v7a.so D:/Qt/Qt5.14.2/5.14.2/android/lib/libQt5Gui_armeabi-v7a.so D:/Qt/Qt5.14.2/5.14.2/android/lib/libQt5QmlModels_armeabi-v7a.so D:/Qt/Qt5.14.2/5.14.2/android/lib/libQt5Qml_armeabi-v7a.so D:/Qt/Qt5.14.2/5.14.2/android/lib/libQt5Network_armeabi-v7a.so D:/Qt/Qt5.14.2/5.14.2/android/lib/libQt5Bluetooth_armeabi-v7a.so D:/Qt/Qt5.14.2/5.14.2/android/lib/libQt5Core_armeabi-v7a.so -lGLESv2   -llog -lz -lm -ldl -lc
AR            = D:\android-sdk_r24.4.1-windows\android-sdk-windows\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar cqs
RANLIB        = D:\android-sdk_r24.4.1-windows\android-sdk-windows\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ranlib
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = armeabi-v7a/

####### Files

SOURCES       = main.cpp \
		device.cpp \
		deviceinfo.cpp \
		httpsclient.cpp \
		serviceinfo.cpp \
		characteristicinfo.cpp armeabi-v7a/qrc_resources.cpp \
		armeabi-v7a/moc_device.cpp \
		armeabi-v7a/moc_deviceinfo.cpp \
		armeabi-v7a/moc_httpsclient.cpp \
		armeabi-v7a/moc_serviceinfo.cpp \
		armeabi-v7a/moc_characteristicinfo.cpp
OBJECTS       = armeabi-v7a/main.obj \
		armeabi-v7a/device.obj \
		armeabi-v7a/deviceinfo.obj \
		armeabi-v7a/httpsclient.obj \
		armeabi-v7a/serviceinfo.obj \
		armeabi-v7a/characteristicinfo.obj \
		armeabi-v7a/qrc_resources.obj \
		armeabi-v7a/moc_device.obj \
		armeabi-v7a/moc_deviceinfo.obj \
		armeabi-v7a/moc_httpsclient.obj \
		armeabi-v7a/moc_serviceinfo.obj \
		armeabi-v7a/moc_characteristicinfo.obj
DIST          = assets/DeviceControl.qml device.h \
		deviceinfo.h \
		httpsclient.h \
		serviceinfo.h \
		characteristicinfo.h main.cpp \
		device.cpp \
		deviceinfo.cpp \
		httpsclient.cpp \
		serviceinfo.cpp \
		characteristicinfo.cpp
QMAKE_TARGET  = liblowenergyscanner_armeabi-v7a.so
DESTDIR       = 
TARGET        = liblowenergyscanner_armeabi-v7a.so


first: all
####### Build rules

liblowenergyscanner_armeabi-v7a.so:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) @armeabi-v7a/object_script.liblowenergyscanner_armeabi-v7a.so.Armeabi-v7a $(OBJCOMP) $(LIBS)

qmake: FORCE
	@$(QMAKE) -o Makefile lowenergyscanner.pro -spec android-clang CONFIG+=debug CONFIG+=qml_debug ANDROID_ABIS=armeabi-v7a

qmake_all: FORCE


all: Makefile liblowenergyscanner_armeabi-v7a.so

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt/Qt5.14.2/5.14.2/android/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents device.h deviceinfo.h httpsclient.h serviceinfo.h characteristicinfo.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp device.cpp deviceinfo.cpp httpsclient.cpp serviceinfo.cpp characteristicinfo.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

aab: apk_install_target
	'D:\Qt\Qt5.14.2\5.14.2\android\bin\androiddeployqt.exe' --input D:/lowenergyscanner/android-lowenergyscanner-deployment-settings.json --output D:/lowenergyscanner/android-build --aab --apk /D/lowenergyscanner/android-build/lowenergyscanner.apk

apk: apk_install_target
	'D:\Qt\Qt5.14.2\5.14.2\android\bin\androiddeployqt.exe' --input D:/lowenergyscanner/android-lowenergyscanner-deployment-settings.json --output D:/lowenergyscanner/android-build --apk /D/lowenergyscanner/android-build/lowenergyscanner.apk

apk_install_target: first
	$(MAKE) -f $(MAKEFILE) INSTALL_ROOT=D:/lowenergyscanner/android-build install

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: armeabi-v7a/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) armeabi-v7a/qrc_resources.cpp
armeabi-v7a/qrc_resources.cpp: resources.qrc \
		../Qt/Qt5.14.2/5.14.2/android/bin/rcc.exe \
		assets/Menu.qml \
		assets/Dialog.qml \
		assets/busy_dark.png \
		assets/Label.qml \
		assets/DeviceControl.qml \
		assets/Characteristics.qml \
		assets/Services.qml \
		assets/Header.qml \
		assets/main.qml
	'D:\Qt\Qt5.14.2\5.14.2\android\bin\rcc.exe' -name resources resources.qrc -o armeabi-v7a/qrc_resources.cpp

compiler_moc_predefs_make_all: armeabi-v7a/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) armeabi-v7a/moc_predefs.h
armeabi-v7a/moc_predefs.h: ../Qt/Qt5.14.2/5.14.2/android/mkspecs/features/data/dummy.cpp
	D:\android-sdk_r24.4.1-windows\android-sdk-windows\ndk\21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -target armv7a-linux-androideabi21 -fno-limit-debug-info -fPIC -fstack-protector-strong -DANDROID -g -marm -O0 -Wall -W -dM -E -o armeabi-v7a/moc_predefs.h ../Qt/Qt5.14.2/5.14.2/android/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: armeabi-v7a/moc_device.cpp armeabi-v7a/moc_deviceinfo.cpp armeabi-v7a/moc_httpsclient.cpp armeabi-v7a/moc_serviceinfo.cpp armeabi-v7a/moc_characteristicinfo.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) armeabi-v7a/moc_device.cpp armeabi-v7a/moc_deviceinfo.cpp armeabi-v7a/moc_httpsclient.cpp armeabi-v7a/moc_serviceinfo.cpp armeabi-v7a/moc_characteristicinfo.cpp
armeabi-v7a/moc_device.cpp: device.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothlocaldevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetoothglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetooth-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QList \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothHostInfo \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothhostinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothAddress \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothaddress.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QByteArray \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariant \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvariant.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdebug.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtextstream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiodevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlocale.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qshareddata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qset.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontiguouscache.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothServiceDiscoveryAgent \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothservicediscoveryagent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothServiceInfo \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothserviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothuuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QtGlobal \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/quuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QDebug \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothDeviceDiscoveryAgent \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothdevicediscoveryagent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothDeviceInfo \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothdeviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocess.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyController \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycontroller.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyAdvertisingData \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergyadvertisingdata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyService \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergyservice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyCharacteristic \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycharacteristic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetooth.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyDescriptor \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergydescriptor.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariantMap \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkReply \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkreply.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtnetworkglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtnetwork-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QIODevice \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkRequest \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkrequest.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedDataPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUrl \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qurl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qurlquery.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkAccessManager \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVector \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QSslConfiguration \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslconfiguration.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtcpsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qabstractsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslerror.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslcertificate.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcryptographichash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdatetime.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qssl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QFlags \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		deviceinfo.h \
		serviceinfo.h \
		characteristicinfo.h \
		armeabi-v7a/moc_predefs.h \
		../Qt/Qt5.14.2/5.14.2/android/bin/moc.exe
	'D:\Qt\Qt5.14.2\5.14.2\android\bin\moc.exe' $(DEFINES) --include D:/lowenergyscanner/armeabi-v7a/moc_predefs.h -ID:/Qt/Qt5.14.2/5.14.2/android/mkspecs/android-clang -ID:/lowenergyscanner -ID:/lowenergyscanner -ID:/Qt/Qt5.14.2/5.14.2/android/include -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQuick -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtGui -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQmlModels -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQml -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtNetwork -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtCore -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/include/c++ -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/9.0.8/include -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/include device.h -o armeabi-v7a/moc_device.cpp

armeabi-v7a/moc_deviceinfo.cpp: deviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothdeviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetoothglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetooth-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothaddress.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QByteArray \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QList \
		armeabi-v7a/moc_predefs.h \
		../Qt/Qt5.14.2/5.14.2/android/bin/moc.exe
	'D:\Qt\Qt5.14.2\5.14.2\android\bin\moc.exe' $(DEFINES) --include D:/lowenergyscanner/armeabi-v7a/moc_predefs.h -ID:/Qt/Qt5.14.2/5.14.2/android/mkspecs/android-clang -ID:/lowenergyscanner -ID:/lowenergyscanner -ID:/Qt/Qt5.14.2/5.14.2/android/include -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQuick -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtGui -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQmlModels -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQml -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtNetwork -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtCore -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/include/c++ -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/9.0.8/include -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/include deviceinfo.h -o armeabi-v7a/moc_deviceinfo.cpp

armeabi-v7a/moc_httpsclient.cpp: httpsclient.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkAccessManager \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtnetworkglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtnetwork-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkrequest.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedDataPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qshareddata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUrl \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qurl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qurlquery.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariant \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvariant.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdebug.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtextstream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiodevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlocale.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qset.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontiguouscache.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVector \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QSslConfiguration \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslconfiguration.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtcpsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qabstractsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslerror.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslcertificate.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcryptographichash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdatetime.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qssl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QFlags \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkReply \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkreply.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QIODevice \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkRequest \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QEventLoop \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qeventloop.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QTimer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtimer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasictimer.h \
		armeabi-v7a/moc_predefs.h \
		../Qt/Qt5.14.2/5.14.2/android/bin/moc.exe
	'D:\Qt\Qt5.14.2\5.14.2\android\bin\moc.exe' $(DEFINES) --include D:/lowenergyscanner/armeabi-v7a/moc_predefs.h -ID:/Qt/Qt5.14.2/5.14.2/android/mkspecs/android-clang -ID:/lowenergyscanner -ID:/lowenergyscanner -ID:/Qt/Qt5.14.2/5.14.2/android/include -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQuick -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtGui -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQmlModels -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQml -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtNetwork -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtCore -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/include/c++ -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/9.0.8/include -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/include httpsclient.h -o armeabi-v7a/moc_httpsclient.cpp

armeabi-v7a/moc_serviceinfo.cpp: serviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyService \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergyservice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothAddress \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothaddress.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetoothglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetooth-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QByteArray \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothuuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QtGlobal \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/quuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QDebug \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdebug.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtextstream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiodevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlocale.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvariant.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qshareddata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qset.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontiguouscache.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyCharacteristic \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycharacteristic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetooth.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyDescriptor \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergydescriptor.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariantMap \
		armeabi-v7a/moc_predefs.h \
		../Qt/Qt5.14.2/5.14.2/android/bin/moc.exe
	'D:\Qt\Qt5.14.2\5.14.2\android\bin\moc.exe' $(DEFINES) --include D:/lowenergyscanner/armeabi-v7a/moc_predefs.h -ID:/Qt/Qt5.14.2/5.14.2/android/mkspecs/android-clang -ID:/lowenergyscanner -ID:/lowenergyscanner -ID:/Qt/Qt5.14.2/5.14.2/android/include -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQuick -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtGui -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQmlModels -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQml -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtNetwork -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtCore -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/include/c++ -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/9.0.8/include -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/include serviceinfo.h -o armeabi-v7a/moc_serviceinfo.cpp

armeabi-v7a/moc_characteristicinfo.cpp: characteristicinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyCharacteristic \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycharacteristic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qshareddata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetooth.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetoothglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetooth-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothuuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QtGlobal \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/quuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QDebug \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdebug.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtextstream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiodevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlocale.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvariant.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qset.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontiguouscache.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyDescriptor \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergydescriptor.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariantMap \
		armeabi-v7a/moc_predefs.h \
		../Qt/Qt5.14.2/5.14.2/android/bin/moc.exe
	'D:\Qt\Qt5.14.2\5.14.2\android\bin\moc.exe' $(DEFINES) --include D:/lowenergyscanner/armeabi-v7a/moc_predefs.h -ID:/Qt/Qt5.14.2/5.14.2/android/mkspecs/android-clang -ID:/lowenergyscanner -ID:/lowenergyscanner -ID:/Qt/Qt5.14.2/5.14.2/android/include -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQuick -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtGui -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQmlModels -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtQml -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtNetwork -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth -ID:/Qt/Qt5.14.2/5.14.2/android/include/QtCore -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/include/c++ -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/lib64/clang/9.0.8/include -ID:/android-sdk_r24.4.1-windows/android-sdk-windows/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/include characteristicinfo.h -o armeabi-v7a/moc_characteristicinfo.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

armeabi-v7a/main.obj: main.cpp ../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QLoggingCategory \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qloggingcategory.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdebug.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtextstream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiodevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlocale.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvariant.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qshareddata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qset.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontiguouscache.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/QQmlContext \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/qqmlcontext.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qurl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qurlquery.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/qjsvalue.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/qtqmlglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/qtqml-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtnetworkglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtnetwork-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/QGuiApplication \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qguiapplication.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qtguiglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qtgui-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreapplication.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qeventloop.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qwindowdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qwindowdefs_win.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qinputmethod.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsize.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmargins.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQuick/QQuickView \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQuick/qquickview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQuick/qquickwindow.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQuick/qtquickglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQuick/qtquick-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQuick/qsgrendererinterface.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQuick/qsgnode.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQuick/qsggeometry.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qopengl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qt_windows.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qopengles2ext.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qopenglext.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QRectF \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrect.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/QMatrix4x4 \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qmatrix4x4.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qvector3d.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qvector4d.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qquaternion.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qgenericmatrix.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdatastream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qwindow.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QEvent \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMargins \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QRect \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qsurface.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qsurfaceformat.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qicon.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qpixmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qpaintdevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qcolor.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qrgb.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qrgba64.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qimage.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qpixelformat.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qtransform.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qmatrix.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qpolygon.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qregion.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qline.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qpainterpath.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qcursor.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qkeysequence.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qfile.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qfiledevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qvector2d.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtGui/qtouchdevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/qqml.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/qqmlprivate.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/qqmlparserstatus.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/qqmlpropertyvaluesource.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/qqmllist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetaobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtQml/qqmldebug.h \
		device.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothlocaldevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetoothglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetooth-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QList \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothHostInfo \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothhostinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothAddress \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothaddress.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QByteArray \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariant \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothServiceDiscoveryAgent \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothservicediscoveryagent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothServiceInfo \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothserviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothuuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QtGlobal \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/quuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QDebug \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothDeviceDiscoveryAgent \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothdevicediscoveryagent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothDeviceInfo \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothdeviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocess.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyController \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycontroller.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyAdvertisingData \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergyadvertisingdata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyService \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergyservice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyCharacteristic \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycharacteristic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetooth.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyDescriptor \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergydescriptor.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariantMap \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkReply \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkreply.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QIODevice \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkRequest \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkrequest.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedDataPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUrl \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkAccessManager \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVector \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QSslConfiguration \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslconfiguration.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtcpsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qabstractsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslerror.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslcertificate.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcryptographichash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdatetime.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qssl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QFlags \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		deviceinfo.h \
		serviceinfo.h \
		characteristicinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/main.obj main.cpp

armeabi-v7a/device.obj: device.cpp device.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothlocaldevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetoothglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetooth-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QList \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothHostInfo \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothhostinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothAddress \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothaddress.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QByteArray \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariant \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvariant.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdebug.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtextstream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiodevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlocale.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qshareddata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qset.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontiguouscache.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothServiceDiscoveryAgent \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothservicediscoveryagent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothServiceInfo \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothserviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothuuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QtGlobal \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/quuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QDebug \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothDeviceDiscoveryAgent \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothdevicediscoveryagent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothDeviceInfo \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothdeviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocess.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyController \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycontroller.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyAdvertisingData \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergyadvertisingdata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyService \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergyservice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyCharacteristic \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycharacteristic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetooth.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyDescriptor \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergydescriptor.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariantMap \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkReply \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkreply.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtnetworkglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtnetwork-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QIODevice \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkRequest \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkrequest.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedDataPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUrl \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qurl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qurlquery.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkAccessManager \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVector \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QSslConfiguration \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslconfiguration.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtcpsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qabstractsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslerror.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslcertificate.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcryptographichash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdatetime.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qssl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QFlags \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		deviceinfo.h \
		serviceinfo.h \
		characteristicinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaEnum \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetaobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QTimer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtimer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasictimer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUrlQuery \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyAdvertisingParameters \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergyadvertisingparameters.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyServiceData \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergyservicedata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyCharacteristicData \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycharacteristicdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/device.obj device.cpp

armeabi-v7a/deviceinfo.obj: deviceinfo.cpp ../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothuuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetoothglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetooth-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QtGlobal \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/quuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QDebug \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdebug.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtextstream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiodevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlocale.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvariant.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qshareddata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qset.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontiguouscache.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer_impl.h \
		deviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothdeviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothaddress.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QByteArray \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QList
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/deviceinfo.obj deviceinfo.cpp

armeabi-v7a/httpsclient.obj: httpsclient.cpp httpsclient.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkAccessManager \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtnetworkglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtnetwork-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkrequest.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedDataPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qshareddata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUrl \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qurl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qurlquery.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariant \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvariant.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdebug.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtextstream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiodevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlocale.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qset.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontiguouscache.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVector \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QSslConfiguration \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslconfiguration.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qtcpsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qabstractsocket.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslerror.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslcertificate.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcryptographichash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdatetime.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qssl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QFlags \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkReply \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/qnetworkreply.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QIODevice \
		../Qt/Qt5.14.2/5.14.2/android/include/QtNetwork/QNetworkRequest \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QEventLoop \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qeventloop.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QTimer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtimer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasictimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/httpsclient.obj httpsclient.cpp

armeabi-v7a/serviceinfo.obj: serviceinfo.cpp serviceinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyService \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergyservice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothAddress \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothaddress.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetoothglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetooth-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QByteArray \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothuuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QtGlobal \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/quuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QDebug \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdebug.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtextstream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiodevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlocale.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvariant.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qshareddata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qset.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontiguouscache.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyCharacteristic \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycharacteristic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetooth.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyDescriptor \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergydescriptor.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariantMap
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/serviceinfo.obj serviceinfo.cpp

armeabi-v7a/characteristicinfo.obj: characteristicinfo.cpp characteristicinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QObject \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnamespace.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig-bootstrapped.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qconfig.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtcore-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsystemdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qprocessordetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcompilerdetection.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtypeinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsysinfo.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlogging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qflags.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbasicatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_bootstrap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qgenericatomic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_cxx11.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qatomic_msvc.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qglobalstatic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmutex.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qnumeric.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qversiontagging.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobjectdefs_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstring.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qchar.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qrefcount.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qarraydata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringliteral.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringview.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringbuilder.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qalgorithms.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiterator.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhashfunctions.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpair.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvector.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainertools_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qpoint.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qbytearraylist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringlist.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qregexp.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qstringmatcher.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcoreevent.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qscopedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmetatype.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvarlengtharray.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontainerfwd.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qobject_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QString \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyCharacteristic \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergycharacteristic.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QSharedPointer \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qshareddata.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qhash.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qsharedpointer_impl.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetooth.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetoothglobal.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qtbluetooth-config.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QBluetoothUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qbluetoothuuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QtGlobal \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QMetaType \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QUuid \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/quuid.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QDebug \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qdebug.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qmap.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qtextstream.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qiodevice.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qlocale.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qvariant.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qset.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/qcontiguouscache.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/QLowEnergyDescriptor \
		../Qt/Qt5.14.2/5.14.2/android/include/QtBluetooth/qlowenergydescriptor.h \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QVariantMap \
		../Qt/Qt5.14.2/5.14.2/android/include/QtCore/QByteArray
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/characteristicinfo.obj characteristicinfo.cpp

armeabi-v7a/qrc_resources.obj: armeabi-v7a/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/qrc_resources.obj armeabi-v7a/qrc_resources.cpp

armeabi-v7a/moc_device.obj: armeabi-v7a/moc_device.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/moc_device.obj armeabi-v7a/moc_device.cpp

armeabi-v7a/moc_deviceinfo.obj: armeabi-v7a/moc_deviceinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/moc_deviceinfo.obj armeabi-v7a/moc_deviceinfo.cpp

armeabi-v7a/moc_httpsclient.obj: armeabi-v7a/moc_httpsclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/moc_httpsclient.obj armeabi-v7a/moc_httpsclient.cpp

armeabi-v7a/moc_serviceinfo.obj: armeabi-v7a/moc_serviceinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/moc_serviceinfo.obj armeabi-v7a/moc_serviceinfo.cpp

armeabi-v7a/moc_characteristicinfo.obj: armeabi-v7a/moc_characteristicinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o armeabi-v7a/moc_characteristicinfo.obj armeabi-v7a/moc_characteristicinfo.cpp

####### Install

install_target: all FORCE
	@test -d $(INSTALL_ROOT:@msyshack@%=%)/libs/armeabi-v7a/ || mkdir -p $(INSTALL_ROOT:@msyshack@%=%)/libs/armeabi-v7a/
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT:@msyshack@%=%)/libs/armeabi-v7a/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT:@msyshack@%=%)/libs/armeabi-v7a/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT:@msyshack@%=%)/libs/armeabi-v7a/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

